apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: asu2022/todoapp
          ports:
            - containerPort: 8080
          env:
            - name: TODO_SERVER_URL
              value: "http://todo-server:8081/api"
      # imagePullSecrets:
      #   - name: my-registry-secret
      # restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  selector:
    app: todo-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30255 # Uncomment for external service
  type: NodePort
